### PR TITLE
Add github actions to build project

### LINKED ISSUE #10: Configure github actions to build project

### PR DESCRIPTION
**Pull request by shellforge**

### CODE REVIEW

**Comment by shellforge** [comment]
#runtest

**Comment by shellforge** [comment]
@runtest

**Comment by shellforge** [comment]
>runtest

**Comment by shellforge** [comment]
:runtest

**Comment by shellforge** [comment]
:runtest

**Comment by shellforge** [comment]
some comment

**Comment by shellforge** [comment]
test comment 2

**Review by maldrake — APPROVED** [review]

**Pull request merged**
